# Generated by Django 5.0 on 2024-02-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='bloodgroup',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
