# Generated by Django 5.0 on 2024-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_registrationform_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
