# Generated by Django 5.0 on 2024-03-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_registrationform_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100),
        ),
    ]
