# Generated by Django 5.0 on 2024-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_registrationform_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='date_remain',
            field=models.DurationField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='donated_date',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('A1B+', 'A1B+'), ('A1B-', 'A1B-'), ('A2B+', 'A2B+'), ('A2B-', 'A2B-')], max_length=100),
        ),
    ]
