# Generated by Django 5.0 on 2024-03-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_registrationform_date_remain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='date_remain',
            field=models.DurationField(default=None),
        ),
    ]
