# Generated by Django 5.0 on 2024-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_alter_registrationform_date_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='date_remain',
            field=models.DurationField(default=None, editable=False),
        ),
    ]
