# Generated by Django 5.0 on 2024-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_alter_registrationform_date_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='donated_date',
            field=models.DateField(),
        ),
    ]
