# Generated by Django 5.0 on 2024-09-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_alter_registrationform_donated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='password',
        ),
    ]
